---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crossplane.services.openmcp.cloud
  resources:
  - crossplanes
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crossplane.services.openmcp.cloud
  resources:
  - crossplanes/finalizers
  - providerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - crossplane.services.openmcp.cloud
  resources:
  - crossplanes/status
  - providerconfigs/status
  verbs:
  - get
  - patch
  - update
