apiVersion: crossplane.services.openmcp.cloud/v1alpha1
kind: ProviderConfig
metadata:
  name: providerconfig-sample
spec:
  chart:
    repository: "https://charts.crossplane.io/stable"
    name: crossplane
    availableVersions:
      - v1.20.0
      - v1.19.0
  availableProviders:
    - name: provider-kuberentes
      package: xpkg.upbound.io/provider-kubernetes
      versions:
        - v0.18.0
        - v0.17.0
    - name: provider-btp
      package: ghcr.io/sap/crossplane-provider-btp
      versions:
        - v1.0.0
        - v0.0.9